export default [
  { value: 3, name: '木工' },
  { value: 2, name: '涂料工' },
  { value: 12, name: '钢筋工' },
  { value: 5, name: '电爆工' },
  { value: 12, name: '水泥工' },
  { value: 5, name: '水电工' },
  { value: 2, name: '搬运工' },
  { value: 5, name: '瓦工' },
  { value: 3, name:"电焊工"},
  { value: 5, name: '其他' },
  { value: 3, name: '木工' },
  { value: 2, name: '涂料工' },
  { value: 12, name: '钢筋工' },
  { value: 5, name: '电爆工' },
  { value: 12, name: '水泥工' },
  { value: 5, name: '水电工' },
  { value: 2, name: '搬运工' },
  { value: 5, name: '瓦工' },
  { value: 3, name:"电焊工"},
  { value: 5, name: '其他' },
  { value: 3, name: '木工' },
  { value: 2, name: '涂料工' },
  { value: 12, name: '钢筋工' },
  { value: 5, name: '电爆工' },
  { value: 12, name: '水泥工' },
  { value: 5, name: '水电工' },
  { value: 2, name: '搬运工' },
  { value: 5, name: '瓦工' },
  { value: 3, name:"电焊工"},
  { value: 5, name: '其他' },
]